---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/french/_index.md
  label: Home page
- type: document
  path: content/french/cabinet/_index.md
  label: Cabinet
- type: directory
  path: content/french/expertises
  label: Expertises
  create: all
  match: "**/*"
- type: document
  path: content/french/offre/_index.md
  label: Notre offre
- type: document
  path: content/french/contact/_index.md
  label: Contact
- type: document
  path: content/french/temoignages/_index.md
  label: Avis clients
- type: directory
  path: content/french/blog
  label: Articles blog
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
